# Generated by Django 4.2 on 2023-04-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Pr name')),
                ('price', models.PositiveIntegerField(verbose_name='Pr price')),
                ('img', models.ImageField(upload_to='images', verbose_name='Pr img')),
            ],
        ),
    ]
